id = "lil"
name = "lil"
version = "0.1.0"
description = "Support for lil is brought to you by this extension."
repository = "https://github.com/brandtcormorant/lil-zed"
authors = ["Brandt Cormorant <brandtcormorant@proton.me>"]
schema_version = 1

[language_servers.lil]
name = "lil"
languages = ["lil"]

[grammars.lil]
repository = "https://github.com/brandtcormorant/tree-sitter-lil"
rev = "7e25cdcd3d3ad049436bc81fced2fe7fc8a1af21"
