id = "lil"
name = "lil"
version = "0.1.0"
description = "Support for lil is brought to you by this extension."
repository = "https://github.com/brandtcormorant/lil-zed"
authors = ["Brandt Cormorant <brandtcormorant@proton.me>"]
schema_version = 1

[language_servers.lil]
name = "lil"
languages = ["lil"]

[grammars.lil]
repository = "https://github.com/brandtcormorant/tree-sitter-lil"
rev = "367aeeeeb4d5ad7509761ed2775f31abd4bc1957"
